### ISSUE TITLE
extensionsToIgnore

### ISSUE THREAD

**Issue by JohannesFerner** [greengerong/prerender-java#33]
Hello,

I would like to allow for prerender/bots to access json files (configuration is stored inside it).
I found the extensionsToIgnore and added .json to it

```

<filter>
        <filter-name>prerender</filter-name>
        <filter-class>com.github.greengerong.PreRenderSEOFilter</filter-class>
        <init-param>
            <param-name>prerenderToken</param-name>
            <param-value>XXXX</param-value>
        </init-param>
        <init-param>
            <param-name>extensionsToIgnore</param-name>
            <param-value>.json</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>prerender</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

```

The strange behaviour tough is that the only thing i get from the server when i want to access a json file (as UA googlebot) is a 504 error message. With the chrome UA it's working fine.

Do you have any suggestions?

br.

**Comment by thoop** [comment]
We cannot render json files through the Prerender browser so we block those extensions. You don't want the crawler to access the files through Prerender. They will request the file normally and get the regular file response from your server. So, everything should work just fine without sending that json file through Prerender.

**Comment by greengerong** [comment]
@JohannesFerner For prerender-java , this client allow you to defined custom resources extensions. But For the JSON file you don't need do like that.JSON file can response as the regular file  from your server.

@thoop @JohannesFerner Thanks. Any update?

**Comment by thoop** [comment]
I don't think this is an issue. Like you said, json files can be sent as a regular file from your server. They don't have to be sent through Prerender. I'd vote to close this issue unless @JohannesFerner has any questions.

**Comment by JohannesFerner** [comment]
Hello @greengerong and @thoop, we can close this issue. 

The unexpected behaviour was not due to the prerender service, it was the integration in our environment - multiple nodes and load-balancing which was causing this issue.
