### ISSUE TITLE
Consider not to autofollow redirects

### ISSUE THREAD

**Issue by lefloh** [greengerong/prerender-java#34]
If prerender-java is running behind a proxy which redirects http requests to https prerender.io will answer with the status code the proxy returns for a http request. 

So http://service.prerender.io/http://my.site will result in the following:

    HTTP/1.1 301 Moved Permanently
    Location: https://my.site

Prerender.io does not follow the 301 to give the crawler a chance to update the index. Unfortunately the HttpClient used by prerender-java will follow this redirect by default so the server will call itself again. 
This can be solved by using the `forwardedURLHeader` param at least if your proxy supports that. (HAProxy for instance [not for version 1.4][1]).

Would it make sense to [disable auto redirect handling][2] or provide an option to disable it? 

 [1]: http://serverfault.com/a/604328
 [2]: http://hc.apache.org/httpcomponents-client-4.3.x/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#disableRedirectHandling()

**Comment by thoop** [comment]
Yes, the HttpClient should not follow the redirect sent back by the Prerender service in order to serve the correct status code back to the crawler so they can update their index.

@greengerong Can you make this change or merge a pull request if @lefloh is able to add it? :)

**Comment by lefloh** [comment]
PR https://github.com/greengerong/prerender-java/pull/35

**Comment by greengerong** [comment]
merged. Thanks everyone.

**Comment by thoop** [comment]
@greengerong thanks so much! You too @lefloh!
