### ISSUE TITLE
Google is still trying to fetch an AJAX page and not a static HTML page.

### ISSUE THREAD

**Issue by divyam** [greengerong/prerender-java#37]
I've built a spring application where the web app is written in AngularJS. When I'm using a **`_escaped_fragment_`** query parameter, the webpage is loading as expected i.e. I get a static HTML page. However, when I'm trying to fetch the page from Google Search Console, it's still trying to render the AJAX page and (ofcourse) failing to give me an informative HTML. Do I need to manually add googlebot in my web.xml? In other words, will including a **crawlerUserAgents init-param** work?

**Existing code snippet in web.xml**
```
<filter>
    <filter-name>prerender</filter-name>
    <filter-class>com.github.greengerong.PreRenderSEOFilter</filter-class>
        <init-param>
            <param-name>prerenderServiceUrl</param-name>
            <param-value>http://128.199.118.113:3000</param-value>
	</init-param>
</filter>
<filter-mapping>
    <filter-name>prerender</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```

**Proposed code snippet in web.xml**
```
<filter>
    <filter-name>prerender</filter-name>
    <filter-class>com.github.greengerong.PreRenderSEOFilter</filter-class>
        <init-param>
            <param-name>prerenderServiceUrl</param-name>
            <param-value>http://128.199.118.113:3000</param-value>
	</init-param>
	<init-param>
            <param-name>crawlerUserAgents</param-name>
            <param-value>Googlebot,Googlebot-Mobile</param-value>
 	</init-param>
</filter>
<filter-mapping>
    <filter-name>prerender</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```

Just to prove that everything else is working fine, please check:
`http://www.labstreet.in/tests/gurgaon/hemoglobin-hb-1`
`http://www.labstreet.in/tests/gurgaon/hemoglobin-hb-1?_escaped_fragment_`
`https://www.dropbox.com/s/jcmgmam4k3se8l0/Screen%20Shot%202016-04-13%20at%208.27.50%20PM.png?dl=0`

**Comment by thoop** [comment]
You should not add Googlebot to the user agent check because you could get penalized for cloaking. If you are trying to test using Fetch as Google, you just need to input the ?_escaped_fragment_= URL into their tool. Fetch as Google is known to have a bug where it doesn't automatically support the escaped fragment crawling protocol even though Googlebot does correctly support the escaped fragment crawling protocol.

**Comment by divyam** [comment]
@thoop That's just what I had been guessing. But are you sure about it? The last line, I mean.

**Comment by thoop** [comment]
Yes, Fetch as Google needs you to enter the `?_escaped_fragment_=` URL manually but Googlebot supports the escaped fragment crawling protocol automatically if you have the `<meta name="fragment" content="!">` tag in the `<head>` of your pages.

**Comment by divyam** [comment]
Thanks. That answers my question.
