### ISSUE TITLE
Illegal domain attribute

### ISSUE THREAD

**Issue by paulux84** [greengerong/prerender-java#41]
Hi,
i'm testing prerender service for site www.weflymate.com but when i try for example [this url](https://www.weflymate.com/?_escaped_fragment_=flightBoard:page;) i get the following warning message from server and 301 redirection to https://www.weflymate.com 
`04:34:01,928 WARN  [org.apache.http.client.protocol.ResponseProcessCookies] (default task-56) Cookie rejected [__cfduid="dc9e47295a5b370645719c1708c7358b81475483641", version:0, domain:weflymate.com, path:/, expiry:Tue Oct 03 04:34:01 EDT 2017] Illegal 'domain' attribute "weflymate.com". Domain of origin: "service.prerender.io"`
What's the problem?
Thanks in advance

**Comment by paulux84** [comment]
You can cancel this issue...the problem is cloudflare redirection

**Comment by joaohencke** [comment]
@paulux84 can we talk about your problem? I'm having the same problem and I cannot find a solution

**Comment by vyankat70war** [comment]
@paulux84 , @joaohencke  I am facing same problem. please help me if you have any solution.
