### ISSUE TITLE
forwardedURLHeader how configure?

### ISSUE THREAD

**Issue by brevleq** [greengerong/prerender-java#42]
Hi, I'm using my application under tomcat 7 behind a nginx server, all the crawl stats in Prerender.io panel is Miss. I've tried configure forwardedURLHeader in the filter, but without sucess:

` private void initPreRenderFilter(ServletContext servletContext, EnumSet<DispatcherType> disps) {
        log.debug("Registering PreRender Filter");
        FilterRegistration.Dynamic preRenderFilter =
                servletContext.addFilter("prerender",
                        new PreRenderSEOFilter());
        preRenderFilter.addMappingForUrlPatterns(disps, true, "/*");
        preRenderFilter.setInitParameter("prerenderToken", "???????");
        preRenderFilter.setInitParameter("forwardedURLHeader", "true");
        preRenderFilter.setAsyncSupported(true);
    }`

Am I configuring this parameter correctly?

**Comment by thoop** [comment]
I think you need to set the forwardedURLHeader equal to the correct URL with the correct protocol. So you'd want to set that in the request lifecycle somewhere.

**Comment by greengerong** [comment]
Any update @brevleq ?

**Comment by brevleq** [comment]
@greengerong The java configuration was correct, however only after I've added **_X-Forwarded-For_** option in nginx it worked.

**Comment by greengerong** [comment]
@brevleq Thanks
