### ISSUE TITLE
Converts my https urls to http before submitting to the Prerender Service

### ISSUE THREAD

**Issue by kgujral** [greengerong/prerender-java#44]
Hi,
I am using this for one of my projects. Below is my java configuration:

```
@Configuration
public class SEOFilterConfig {

  @Value("${prerender.service.url}")
  private String prerenderServiceUrl;

  @Bean
  public FilterRegistrationBean someFilterRegistration() {
    FilterRegistrationBean registration = new FilterRegistrationBean();
    registration.setFilter(seoFilter());
    registration.setName("prerender");
    registration.addUrlPatterns("/*");
    registration.addInitParameter("prerenderServiceUrl", prerenderServiceUrl);
    registration.addInitParameter("prerenderToken", "mytoken");
    return registration;
  }

  @Bean(name = "seoFilter")
  public Filter seoFilter() {
    return new PreRenderSEOFilter();
  }
}
```

My pom is as follows:
```
<dependency>
	<groupId>com.github.greengerong</groupId>
	<artifactId>prerender-java</artifactId>
	<version>1.6.4</version>
</dependency>
```

Everything is working but there is only one problem, all my urls are getting converted to non-https before being submitted to prerender service as I can see in `https://prerender.io/crawl-stats` here.

Please suggest a way out of this. Thanks.

**Comment by thoop** [comment]
You might want to use the forwardedURLHeader option and use the header that you pick to set the original https URL to be used when sent to Prerender:

https://github.com/greengerong/prerender-java#forwardedurlheader

Otherwise, you could add an option to the java middleware to force the protocol to https if you wanted to open a pull request! :)

**Comment by thoop** [comment]
Sure! In the `getRequestUrl` function:

https://github.com/greengerong/prerender-java/blob/master/src/main/java/com/github/greengerong/PrerenderSeoService.java#L181

You would want it to look something like:
```
    private String getRequestURL(HttpServletRequest request) {
        if (prerenderConfig.getForwardedURLHeader() != null) {
            String url = request.getHeader(prerenderConfig.getForwardedURLHeader());
            if (url != null) {
                return url;
            }
        }

        if (prerenderConfig.getProtocol() != null) {
            String url = request.getRequestURL().toString();
            return url.replace(request.getScheme(), prerenderConfig.getProtocol());
        }

        return request.getRequestURL().toString();
    }
```

You'd need to add the config methods in the PrerenderConfig.java file. I didn't test the above code so you'll want to test and modify that if needed. Also, if you could add some documentation on the readme.md, that would be awesome too! Let me know if you have any questions.

Thanks a ton!

**Comment by kgujral** [comment]
Thanks for the pointer, I have created a PR. Let me know in case something is missing. Thanks!

**Comment by thoop** [comment]
Thanks so much!

**Comment by greengerong** [comment]
merged
